title: "Yanlin's Homepage"
email: yanlin.fu2002@gmail.com
author: Yanlin Fu

description: >-
  Academic homepage and notes on mathematical logic, cognitive neuroscience,
  artificial intelligence, physics, and mathematical modeling.

lang: zh-CN
url: "https://10eit.github.io"

github_username: 10eit

theme: minima

header_pages:
  - writing.markdown
  - research.markdown
  - miscellany.markdown

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM

collections:
  ideas:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Yanlin Fu
      mathjax: true
