title: 绿色猪头的博客
email: yanlin.fu2002@gmail.com
author: 绿色猪头

description: >-

github_username: 10eit

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: 绿色猪头
      mathjax: true